# Let's Chat: Docker Compose
# https://docs.docker.com/compose/
#
# Usage: docker-compose up
version: '3'
services:
  app:
    image: sdelements/lets-chat:latest
    links:
      - mongo
    ports:
      - 80:8080
      - 5222:5222
  
  mongo:
    image: mongo:latest
